alpha: 0.2
batch_size: 128
actor_lr: 0.0003
critic_lr: 0.0003
gamma: 0.99

state_dim: 17
action_dim: 3
hidden_sizes: 256
max_action: 1

gaussian_noise_std: 1.0
eta: 0.1

temperature_opt: False

tau: 0.005
update_interval: 2
expl_noise: 0.2

eval_episode: 10
eval_freq: 2500
start_steps: 5000
max_step: 500000

device: cuda

save_freq: 5000

lam: 0.7
temp: 3.0
eta: 0.1


weight: 2.5




# gravity 0.5
# src rollout length 2, 
# trg rollout length 1, 
# src rollout with src 5, 
# bc 0.05, 
# env_penalty_coef 2.5, 
# penalty_coef 0.1, 
# trg_ratio 0.1
# rollout target state: 250
# q_weighted: 1